@startuml
left to right direction

interface Term
interface Atom
interface Struct
interface Collection

interface Empty {
  ' + {static} list(): EmptyList
  ' + {static} set(): EmptySet
}
interface EmptySet {
  ' + {static} invoke(): EmptySet
}
interface Set {
  ' + unfoldedArray: Array<Term>
  ' + unfoldedList: List<Term>
  ' + unfoldedSequence: Sequence<Term>
  ' + toArray(): Array<Term>
  ' + toList(): List<Term>
  ' + toSequence(): Sequence<Term>
  ' + {static} empty(): Set
  ' + {static} of(**varargs** items: Term): Set
  ' + {static} of(items: Iterable<Term>): Set
}

Term <|-- Struct
Struct <|-- Collection
Struct <|-- Atom

Collection <|-- Set

Atom <|-- Empty

Empty <|-- EmptySet

Set <|-- EmptySet

@enduml