@startuml
left to right direction

interface Term
interface Constant
interface Atom 

interface Truth {
  + isTrue: Boolean
  + isFail: Boolean
  ' + {static} of(value: Boolean): Truth
}

Term <|-down- Constant

Constant <|-down- Atom

Atom <|-down- Truth

@enduml