@startuml
left to right direction

interface Term 

interface Var {
  + name: String
  + completeName: String
  + id: String
  + isAnonymous: Boolean
  ' + {static} of(name: String): Var
}
Term <|-- Var
@enduml